version: '3'
services:
  postgres_db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: stackoverflow_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: letitr@in
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /home/deepankaracharyya/StackOverflow/DB_per_storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"
